// 200문항 인성검사 데이터
// dim: L(거짓말척도) E(외향성) C(성실성) A(친화성) O(개방성)
//      N(정서안정성) S(사회성) R(리더십) T(스트레스내성) P(적극성)
// rev: true = 역채점

export const ALL_QUESTIONS = [
  // ── 거짓말 척도 L (15) ──
  { id: 1,  text: "나는 지금까지 한 번도 거짓말을 한 적이 없다.", dim: "L", rev: false },
  { id: 2,  text: "나는 언제나 약속을 빠짐없이 지킨다.", dim: "L", rev: false },
  { id: 3,  text: "나는 남의 험담을 한 번도 한 적이 없다.", dim: "L", rev: false },
  { id: 4,  text: "나는 한 번도 다른 사람을 질투하거나 시기한 적이 없다.", dim: "L", rev: false },
  { id: 5,  text: "나는 지각을 단 한 번도 한 적이 없다.", dim: "L", rev: false },
  { id: 6,  text: "나는 모든 사람에게 항상 친절하다.", dim: "L", rev: false },
  { id: 7,  text: "나는 화를 낸 적이 단 한 번도 없다.", dim: "L", rev: false },
  { id: 8,  text: "나는 개인적인 이익을 위해 행동한 적이 한 번도 없다.", dim: "L", rev: false },
  { id: 9,  text: "나는 한 번도 나쁜 생각을 한 적이 없다.", dim: "L", rev: false },
  { id: 10, text: "나는 어떤 상황에서도 거짓말을 하지 않는다.", dim: "L", rev: false },
  { id: 11, text: "나는 실수를 한 적이 없다.", dim: "L", rev: false },
  { id: 12, text: "나는 항상 솔직하게 말한다.", dim: "L", rev: false },
  { id: 13, text: "나는 불공정한 상황에서도 불평을 한 적이 없다.", dim: "L", rev: false },
  { id: 14, text: "나는 다른 사람의 성공을 항상 진심으로 기뻐한다.", dim: "L", rev: false },
  { id: 15, text: "나는 항상 규칙과 원칙을 철저히 지킨다.", dim: "L", rev: false },
  // ── 외향성 E (20) ──
  { id: 16, text: "처음 만난 사람과도 쉽게 대화를 나눌 수 있다.", dim: "E", rev: false },
  { id: 17, text: "많은 사람들이 모인 자리에서 에너지가 생긴다.", dim: "E", rev: false },
  { id: 18, text: "혼자 있는 것보다 여러 사람과 함께 있는 것이 좋다.", dim: "E", rev: false },
  { id: 19, text: "발표나 프레젠테이션을 즐기는 편이다.", dim: "E", rev: false },
  { id: 20, text: "새로운 사람을 만나는 것이 즐겁다.", dim: "E", rev: false },
  { id: 21, text: "나는 대화에서 주도권을 잡는 편이다.", dim: "E", rev: false },
  { id: 22, text: "집에 혼자 있기보다 밖에서 활동하는 것이 좋다.", dim: "E", rev: false },
  { id: 23, text: "사람들 앞에 나서는 것을 두려워하지 않는다.", dim: "E", rev: false },
  { id: 24, text: "다양한 활동에 적극적으로 참여한다.", dim: "E", rev: false },
  { id: 25, text: "나는 조용한 것보다 활동적인 환경을 선호한다.", dim: "E", rev: false },
  { id: 26, text: "파티나 모임 자리가 불편하다.", dim: "E", rev: true },
  { id: 27, text: "나는 가급적 사람들과의 만남을 피하려 한다.", dim: "E", rev: true },
  { id: 28, text: "낯선 환경에서 쉽게 적응한다.", dim: "E", rev: false },
  { id: 29, text: "나는 먼저 말을 거는 편이다.", dim: "E", rev: false },
  { id: 30, text: "여러 사람 앞에서 말할 때 자신감이 있다.", dim: "E", rev: false },
  { id: 31, text: "사람들과 어울리는 것보다 혼자 있는 것이 편하다.", dim: "E", rev: true },
  { id: 32, text: "나는 사교 모임을 좋아한다.", dim: "E", rev: false },
  { id: 33, text: "새로운 관계를 맺는 것이 즐겁다.", dim: "E", rev: false },
  { id: 34, text: "나는 사람들에게 먼저 말을 걸기보다 기다리는 편이다.", dim: "E", rev: true },
  { id: 35, text: "활발하고 적극적이라는 말을 자주 듣는다.", dim: "E", rev: false },
  // ── 성실성 C (25) ──
  { id: 36, text: "맡은 일은 끝까지 완수한다.", dim: "C", rev: false },
  { id: 37, text: "계획을 세우고 그 계획에 따라 행동하는 편이다.", dim: "C", rev: false },
  { id: 38, text: "나는 마감 기한을 철저히 지킨다.", dim: "C", rev: false },
  { id: 39, text: "일을 미루는 경향이 있다.", dim: "C", rev: true },
  { id: 40, text: "나는 세부 사항에 주의를 기울인다.", dim: "C", rev: false },
  { id: 41, text: "나는 규칙적인 생활을 유지한다.", dim: "C", rev: false },
  { id: 42, text: "어떤 일을 시작하면 반드시 마무리 짓는다.", dim: "C", rev: false },
  { id: 43, text: "나는 조직적이고 체계적으로 일한다.", dim: "C", rev: false },
  { id: 44, text: "즉흥적으로 행동하는 경향이 있다.", dim: "C", rev: true },
  { id: 45, text: "나는 책임감이 강한 편이다.", dim: "C", rev: false },
  { id: 46, text: "나는 목표를 세우고 꾸준히 노력한다.", dim: "C", rev: false },
  { id: 47, text: "일의 우선순위를 잘 파악하고 정리한다.", dim: "C", rev: false },
  { id: 48, text: "중요한 약속이나 일정을 잊어버린 적이 있다.", dim: "C", rev: true },
  { id: 49, text: "나는 스스로 동기를 부여하며 일한다.", dim: "C", rev: false },
  { id: 50, text: "나는 완벽하게 마무리하는 것을 중요시한다.", dim: "C", rev: false },
  { id: 51, text: "나는 꼼꼼하게 확인하는 편이다.", dim: "C", rev: false },
  { id: 52, text: "나는 자기 관리를 잘 한다.", dim: "C", rev: false },
  { id: 53, text: "어려운 상황에서도 포기하지 않는다.", dim: "C", rev: false },
  { id: 54, text: "나는 게으른 편이다.", dim: "C", rev: true },
  { id: 55, text: "나는 항상 준비된 상태를 유지하려 한다.", dim: "C", rev: false },
  { id: 56, text: "나는 장기적인 목표를 향해 꾸준히 노력한다.", dim: "C", rev: false },
  { id: 57, text: "나는 업무 중에 자주 집중력을 잃는다.", dim: "C", rev: true },
  { id: 58, text: "나는 일하면서 실수를 최소화하려 노력한다.", dim: "C", rev: false },
  { id: 59, text: "나는 나태해지는 순간 스스로 다잡는 편이다.", dim: "C", rev: false },
  { id: 60, text: "나는 성과를 내기 위해 추가 시간을 투자한다.", dim: "C", rev: false },
  // ── 친화성 A (20) ──
  { id: 61, text: "다른 사람의 감정을 잘 이해한다.", dim: "A", rev: false },
  { id: 62, text: "나는 협력을 중요하게 생각한다.", dim: "A", rev: false },
  { id: 63, text: "갈등 상황에서 양보하는 편이다.", dim: "A", rev: false },
  { id: 64, text: "타인의 의견을 존중하고 경청한다.", dim: "A", rev: false },
  { id: 65, text: "나는 이타적인 편이다.", dim: "A", rev: false },
  { id: 66, text: "나는 팀원들과 조화를 이루며 일하는 것이 좋다.", dim: "A", rev: false },
  { id: 67, text: "타인의 어려움을 보면 돕고 싶은 마음이 생긴다.", dim: "A", rev: false },
  { id: 68, text: "나는 경쟁보다 협력을 선호한다.", dim: "A", rev: false },
  { id: 69, text: "나는 상대방의 입장에서 생각해보려 한다.", dim: "A", rev: false },
  { id: 70, text: "나는 다른 사람의 의견보다 내 생각을 더 중요시한다.", dim: "A", rev: true },
  { id: 71, text: "나는 다른 사람에 대해 비판적인 편이다.", dim: "A", rev: true },
  { id: 72, text: "나는 양보하는 것이 손해라고 느낀다.", dim: "A", rev: true },
  { id: 73, text: "동료의 성공을 진심으로 축하해줄 수 있다.", dim: "A", rev: false },
  { id: 74, text: "나는 나만의 방식을 고집하는 편이다.", dim: "A", rev: true },
  { id: 75, text: "나는 주변 사람들의 감정에 민감하게 반응한다.", dim: "A", rev: false },
  { id: 76, text: "남의 부탁을 거절하는 것이 어렵다.", dim: "A", rev: false },
  { id: 77, text: "나는 사람들 사이의 갈등을 중재하려 한다.", dim: "A", rev: false },
  { id: 78, text: "나는 불합리한 상황에서도 감정적으로 반응하지 않는다.", dim: "A", rev: false },
  { id: 79, text: "나는 남을 쉽게 신뢰한다.", dim: "A", rev: false },
  { id: 80, text: "나는 갈등을 피하려 한다.", dim: "A", rev: false },
  // ── 개방성 O (20) ──
  { id: 81, text: "새로운 아이디어와 개념에 흥미를 느낀다.", dim: "O", rev: false },
  { id: 82, text: "나는 창의적인 사람이라고 생각한다.", dim: "O", rev: false },
  { id: 83, text: "다양한 문화와 생각에 관심이 많다.", dim: "O", rev: false },
  { id: 84, text: "나는 변화를 두려워하지 않는다.", dim: "O", rev: false },
  { id: 85, text: "새로운 방식으로 문제를 해결하는 것을 즐긴다.", dim: "O", rev: false },
  { id: 86, text: "나는 예술, 문학, 음악 등에 관심이 있다.", dim: "O", rev: false },
  { id: 87, text: "기존의 방식보다 새로운 방법을 시도하고 싶다.", dim: "O", rev: false },
  { id: 88, text: "나는 상상력이 풍부한 편이다.", dim: "O", rev: false },
  { id: 89, text: "익숙한 것이 새로운 것보다 편하다.", dim: "O", rev: true },
  { id: 90, text: "나는 호기심이 많다.", dim: "O", rev: false },
  { id: 91, text: "나는 다양한 분야에 관심을 갖는다.", dim: "O", rev: false },
  { id: 92, text: "반복적인 업무보다 창의적인 업무가 더 잘 맞는다.", dim: "O", rev: false },
  { id: 93, text: "나는 고정된 루틴이 더 편하다.", dim: "O", rev: true },
  { id: 94, text: "복잡한 문제를 분석하고 탐구하는 것이 즐겁다.", dim: "O", rev: false },
  { id: 95, text: "나는 실험적인 것보다 검증된 방법을 선호한다.", dim: "O", rev: true },
  { id: 96, text: "나는 다양한 시각에서 상황을 바라보려 한다.", dim: "O", rev: false },
  { id: 97, text: "나는 추상적인 개념보다 구체적인 것을 선호한다.", dim: "O", rev: true },
  { id: 98, text: "나는 현상의 이면에 있는 이유를 궁금해한다.", dim: "O", rev: false },
  { id: 99, text: "나는 틀에 박힌 사고를 벗어나려 한다.", dim: "O", rev: false },
  { id: 100, text: "새로운 환경에 놓이면 기대감이 생긴다.", dim: "O", rev: false },
  // ── 정서 안정성 N (25) ──
  { id: 101, text: "나는 감정 기복이 심하지 않다.", dim: "N", rev: false },
  { id: 102, text: "스트레스 상황에서도 침착함을 유지한다.", dim: "N", rev: false },
  { id: 103, text: "나는 쉽게 불안해진다.", dim: "N", rev: true },
  { id: 104, text: "비판을 받으면 매우 상처를 받는다.", dim: "N", rev: true },
  { id: 105, text: "나는 평소에 걱정이 많다.", dim: "N", rev: true },
  { id: 106, text: "나는 기분이 자주 변한다.", dim: "N", rev: true },
  { id: 107, text: "나는 감정을 잘 통제한다.", dim: "N", rev: false },
  { id: 108, text: "위기 상황에서도 냉정하게 판단한다.", dim: "N", rev: false },
  { id: 109, text: "나는 작은 실수에도 오래 자책한다.", dim: "N", rev: true },
  { id: 110, text: "나는 예민한 편이다.", dim: "N", rev: true },
  { id: 111, text: "나는 부정적인 감정을 잘 이겨낸다.", dim: "N", rev: false },
  { id: 112, text: "나는 다른 사람의 말에 쉽게 흔들린다.", dim: "N", rev: true },
  { id: 113, text: "어려운 상황에서도 긍정적인 면을 찾는다.", dim: "N", rev: false },
  { id: 114, text: "나는 압박감 속에서 잘 일한다.", dim: "N", rev: false },
  { id: 115, text: "나는 실패해도 빨리 회복한다.", dim: "N", rev: false },
  { id: 116, text: "나는 화가 났을 때 행동을 자제하기 어렵다.", dim: "N", rev: true },
  { id: 117, text: "나는 미래에 대해 자주 불안해한다.", dim: "N", rev: true },
  { id: 118, text: "나는 무기력함을 자주 느낀다.", dim: "N", rev: true },
  { id: 119, text: "나는 정서적으로 안정적인 편이다.", dim: "N", rev: false },
  { id: 120, text: "나는 어떤 상황에서도 자기 자신을 잃지 않는다.", dim: "N", rev: false },
  { id: 121, text: "나는 사소한 일로도 감정이 상하는 편이다.", dim: "N", rev: true },
  { id: 122, text: "나는 감정적으로 흥분하는 일이 드물다.", dim: "N", rev: false },
  { id: 123, text: "나는 타인의 평가에 지나치게 신경 쓴다.", dim: "N", rev: true },
  { id: 124, text: "나는 실수나 비판 이후에도 자신감을 유지한다.", dim: "N", rev: false },
  { id: 125, text: "나는 감정보다 이성으로 판단하는 편이다.", dim: "N", rev: false },
  // ── 사회성 S (20) ──
  { id: 126, text: "나는 처음 보는 사람에게도 편하게 다가간다.", dim: "S", rev: false },
  { id: 127, text: "나는 다양한 사람들과 잘 어울린다.", dim: "S", rev: false },
  { id: 128, text: "나는 인간관계가 넓은 편이다.", dim: "S", rev: false },
  { id: 129, text: "나는 친구를 쉽게 사귄다.", dim: "S", rev: false },
  { id: 130, text: "나는 사람들 사이에서 분위기를 밝게 만든다.", dim: "S", rev: false },
  { id: 131, text: "나는 다른 사람의 고민을 잘 들어준다.", dim: "S", rev: false },
  { id: 132, text: "나는 사람들에게 호감을 받는 편이다.", dim: "S", rev: false },
  { id: 133, text: "나는 사교적이라는 말을 자주 듣는다.", dim: "S", rev: false },
  { id: 134, text: "나는 모르는 사람에게 말을 거는 것이 어렵다.", dim: "S", rev: true },
  { id: 135, text: "나는 팀 내에서 중재자 역할을 한 적이 있다.", dim: "S", rev: false },
  { id: 136, text: "나는 사람들이 나를 좋아한다고 느낀다.", dim: "S", rev: false },
  { id: 137, text: "나는 다른 사람의 필요를 잘 파악한다.", dim: "S", rev: false },
  { id: 138, text: "나는 상대방의 감정을 잘 읽는다.", dim: "S", rev: false },
  { id: 139, text: "나는 어색한 상황을 잘 풀어가는 편이다.", dim: "S", rev: false },
  { id: 140, text: "나는 인맥을 중요하게 생각한다.", dim: "S", rev: false },
  { id: 141, text: "나는 다른 사람의 입장을 배려하며 말한다.", dim: "S", rev: false },
  { id: 142, text: "나는 소통에 어려움을 느끼는 경우가 많다.", dim: "S", rev: true },
  { id: 143, text: "나는 집단에서 분위기 파악을 잘 한다.", dim: "S", rev: false },
  { id: 144, text: "나는 관계 유지에 노력을 기울인다.", dim: "S", rev: false },
  { id: 145, text: "나는 대인관계에서 갈등이 생기는 것을 두려워한다.", dim: "S", rev: true },
  // ── 리더십 R (20) ──
  { id: 146, text: "나는 목표를 설정하고 팀을 이끄는 것을 좋아한다.", dim: "R", rev: false },
  { id: 147, text: "나는 어려운 결정을 혼자 내리는 것이 힘들다.", dim: "R", rev: true },
  { id: 148, text: "나는 다른 사람들에게 영향력을 줄 수 있다.", dim: "R", rev: false },
  { id: 149, text: "나는 모임이나 팀에서 자연스럽게 리더 역할을 맡게 된다.", dim: "R", rev: false },
  { id: 150, text: "나는 결단력이 있다.", dim: "R", rev: false },
  { id: 151, text: "나는 팀원의 강점을 파악하고 적절히 분배할 수 있다.", dim: "R", rev: false },
  { id: 152, text: "나는 어려운 상황에서도 주도적으로 행동한다.", dim: "R", rev: false },
  { id: 153, text: "나는 타인에게 동기를 부여할 수 있다.", dim: "R", rev: false },
  { id: 154, text: "나는 리더보다 팔로워 역할이 더 편하다.", dim: "R", rev: true },
  { id: 155, text: "나는 책임지는 것이 부담스럽다.", dim: "R", rev: true },
  { id: 156, text: "나는 비전을 제시하고 설득할 수 있다.", dim: "R", rev: false },
  { id: 157, text: "나는 갈등 상황에서 해결책을 제시한다.", dim: "R", rev: false },
  { id: 158, text: "나는 혼자 잘하는 것보다 팀을 잘 이끄는 것이 더 중요하다고 생각한다.", dim: "R", rev: false },
  { id: 159, text: "나는 부하직원이나 후배를 잘 이끌 자신이 있다.", dim: "R", rev: false },
  { id: 160, text: "나는 상황을 전체적으로 파악하고 계획을 세운다.", dim: "R", rev: false },
  { id: 161, text: "나는 팀의 성과에 대해 책임감을 느낀다.", dim: "R", rev: false },
  { id: 162, text: "나는 팀원들에게 명확하게 지시할 수 있다.", dim: "R", rev: false },
  { id: 163, text: "나는 위기 상황에서 팀을 안정시킬 수 있다.", dim: "R", rev: false },
  { id: 164, text: "나는 권위보다 신뢰를 통해 사람들을 이끈다.", dim: "R", rev: false },
  { id: 165, text: "나는 방향성이 불분명할 때 먼저 나서서 정리한다.", dim: "R", rev: false },
  // ── 스트레스 내성 T (20) ──
  { id: 166, text: "나는 업무량이 많아도 큰 부담을 느끼지 않는다.", dim: "T", rev: false },
  { id: 167, text: "마감 압박이 심해도 침착하게 일할 수 있다.", dim: "T", rev: false },
  { id: 168, text: "나는 스트레스를 받으면 일의 효율이 떨어진다.", dim: "T", rev: true },
  { id: 169, text: "나는 동시에 여러 가지 일을 처리하는 것이 어렵다.", dim: "T", rev: true },
  { id: 170, text: "나는 실패한 후에도 금방 다시 시작할 수 있다.", dim: "T", rev: false },
  { id: 171, text: "나는 압박이 심한 상황에서도 최선을 다한다.", dim: "T", rev: false },
  { id: 172, text: "나는 어려운 상황에서도 유머 감각을 잃지 않는다.", dim: "T", rev: false },
  { id: 173, text: "나는 번아웃(소진)을 자주 경험한다.", dim: "T", rev: true },
  { id: 174, text: "나는 갑작스러운 변화에 잘 적응한다.", dim: "T", rev: false },
  { id: 175, text: "나는 비난이나 압박을 받아도 흔들리지 않는다.", dim: "T", rev: false },
  { id: 176, text: "나는 장기적인 목표를 향해 꾸준히 버틸 수 있다.", dim: "T", rev: false },
  { id: 177, text: "나는 어려움이 생기면 쉽게 지치는 편이다.", dim: "T", rev: true },
  { id: 178, text: "나는 불확실한 상황에서도 집중력을 유지한다.", dim: "T", rev: false },
  { id: 179, text: "나는 힘든 일이 있어도 다음 날 다시 활기차게 시작한다.", dim: "T", rev: false },
  { id: 180, text: "나는 장시간 집중해서 일할 수 있다.", dim: "T", rev: false },
  { id: 181, text: "나는 반복되는 실패에도 포기하지 않는다.", dim: "T", rev: false },
  { id: 182, text: "나는 모욕적인 말을 들어도 감정적으로 반응하지 않는다.", dim: "T", rev: false },
  { id: 183, text: "나는 업무 외 스트레스가 업무에 영향을 미친다.", dim: "T", rev: true },
  { id: 184, text: "나는 회복탄력성이 강한 편이다.", dim: "T", rev: false },
  { id: 185, text: "나는 감당하기 어려운 상황에서 도움을 요청할 수 있다.", dim: "T", rev: false },
  // ── 적극성 P (15) ──
  { id: 186, text: "나는 아이디어가 생기면 즉시 실행에 옮긴다.", dim: "P", rev: false },
  { id: 187, text: "나는 도전적인 목표를 좋아한다.", dim: "P", rev: false },
  { id: 188, text: "나는 목표를 달성하기 위해 끈질기게 노력한다.", dim: "P", rev: false },
  { id: 189, text: "나는 문제를 발견하면 즉시 해결하려 한다.", dim: "P", rev: false },
  { id: 190, text: "나는 기회가 생기면 적극적으로 잡는다.", dim: "P", rev: false },
  { id: 191, text: "나는 필요하다고 생각하면 먼저 변화를 이끈다.", dim: "P", rev: false },
  { id: 192, text: "나는 결과가 불확실해도 시도한다.", dim: "P", rev: false },
  { id: 193, text: "나는 위험을 감수하는 것이 어렵다.", dim: "P", rev: true },
  { id: 194, text: "나는 새로운 것을 배우고 도전하는 것을 즐긴다.", dim: "P", rev: false },
  { id: 195, text: "나는 높은 기준을 스스로에게 적용한다.", dim: "P", rev: false },
  { id: 196, text: "나는 남들이 포기한 일도 해낼 수 있다고 믿는다.", dim: "P", rev: false },
  { id: 197, text: "나는 주어진 것보다 더 많은 것을 하려 한다.", dim: "P", rev: false },
  { id: 198, text: "나는 현상에 안주하는 편이다.", dim: "P", rev: true },
  { id: 199, text: "나는 일에서 성취감을 중요하게 여긴다.", dim: "P", rev: false },
  { id: 200, text: "나는 행동보다 계획에 더 많은 시간을 쓴다.", dim: "P", rev: true },
];

export const DIM_META = {
  E: { label: "외향성",       color: "#6366F1", desc: "사교성·활동 에너지" },
  C: { label: "성실성",       color: "#0EA5E9", desc: "책임감·꼼꼼함" },
  A: { label: "친화성",       color: "#10B981", desc: "협력·배려 능력" },
  O: { label: "개방성",       color: "#F59E0B", desc: "창의성·호기심" },
  N: { label: "정서 안정성",  color: "#8B5CF6", desc: "감정 통제·안정성" },
  S: { label: "사회성",       color: "#EC4899", desc: "대인관계 능력" },
  R: { label: "리더십",       color: "#EF4444", desc: "주도력·결단력" },
  T: { label: "스트레스 내성",color: "#14B8A6", desc: "압박·적응력" },
  P: { label: "적극성",       color: "#F97316", desc: "추진력·도전정신" },
};
